### ISSUE TITLE
The default ssh-agent doesn't work on non-x86, need to install tomcat native version

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/buildfarm_deployment#138]
This is a known issue: https://issues.jenkins-ci.org/browse/JENKINS-30746

The workaround is to install the tomcat native library as an alternative implementation. 

`libtcnative-1`

You get errors like this: 

```
[ssh-agent] Looking for ssh-agent implementation...
[ssh-agent]   Java/JNR ssh-agent
[ssh-agent] FATAL: Could not find a suitable ssh-agent provider
[ssh-agent] Diagnostic report
[ssh-agent] * Java/JNR ssh-agent
[ssh-agent]     java.io.IOException: Remote call on tx1-alpha-c9863dce failed
[ssh-agent]         at hudson.remoting.Channel.call(Channel.java:789)
[ssh-agent]         at com.cloudbees.jenkins.plugins.sshagent.jna.JNRRemoteAgentFactory.start(JNRRemoteAgentFactory.java:61)
[ssh-agent]         at com.cloudbees.jenkins.plugins.sshagent.SSHAgentBuildWrapper$SSHAgentEnvironment.<init>(SSHAgentBuildWrapper.java:353)
[ssh-agent]         at com.cloudbees.jenkins.plugins.sshagent.SSHAgentBuildWrapper.createSSHAgentEnvironment(SSHAgentBuildWrapper.java:246)
[ssh-agent]         at com.cloudbees.jenkins.plugins.sshagent.SSHAgentBuildWrapper.preCheckout(SSHAgentBuildWrapper.java:223)
[ssh-agent]         at jenkins.scm.SCMCheckoutStrategy.preCheckout(SCMCheckoutStrategy.java:76)
[ssh-agent]         at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:528)
[ssh-agent]         at hudson.model.Run.execute(Run.java:1738)
[ssh-agent]         at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
[ssh-agent]         at hudson.model.ResourceController.execute(ResourceController.java:98)
[ssh-agent]         at hudson.model.Executor.run(Executor.java:410)
[ssh-agent]     Caused by: java.lang.UnsatisfiedLinkError: could not load FFI provider jnr.ffi.provider.jffi.Provider
[ssh-agent]         at jnr.ffi.provider.InvalidRuntime.newLoadError(InvalidRuntime.java:83)
[ssh-agent]         at jnr.ffi.provider.InvalidRuntime.findType(InvalidRuntime.java:24)
[ssh-agent]         at jnr.ffi.Struct$NumberField.<init>(Struct.java:649)
[ssh-agent]         at jnr.ffi.Struct$Unsigned16.<init>(Struct.java:1007)
[ssh-agent]         at jnr.unixsocket.SockAddrUnix$DefaultSockAddrUnix.<init>(SockAddrUnix.java:129)
[ssh-agent]         at jnr.unixsocket.SockAddrUnix.create(SockAddrUnix.java:99)
[ssh-agent]         at jnr.unixsocket.UnixSocketAddress.<init>(UnixSocketAddress.java:32)
[ssh-agent]         at com.cloudbees.jenkins.plugins.sshagent.jna.AgentServer.start(AgentServer.java:80)
[ssh-agent]         at com.cloudbees.jenkins.plugins.sshagent.jna.JNRRemoteAgent.<init>(JNRRemoteAgent.java:68)
[ssh-agent]         at com.cloudbees.jenkins.plugins.sshagent.jna.JNRRemoteAgentStarter.call(JNRRemoteAgentStarter.java:63)
[ssh-agent]         at com.cloudbees.jenkins.plugins.sshagent.jna.JNRRemoteAgentStarter.call(JNRRemoteAgentStarter.java:37)
[ssh-agent]         at hudson.remoting.UserRequest.perform(UserRequest.java:121)
[ssh-agent]         at hudson.remoting.UserRequest.perform(UserRequest.java:49)
[ssh-agent]         at hudson.remoting.Request$2.run(Request.java:324)
[ssh-agent]         at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
[ssh-agent]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ssh-agent]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[ssh-agent]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[ssh-agent]         at hudson.remoting.Engine$1$1.run(Engine.java:63)
[ssh-agent]         at java.lang.Thread.run(Thread.java:745)
[ssh-agent]         at ......remote call to tx1-alpha-c9863dce(Native Method)
[ssh-agent]         at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1416)
[ssh-agent]         at hudson.remoting.UserResponse.retrieve(UserRequest.java:220)
[ssh-agent]         at hudson.remoting.Channel.call(Channel.java:781)
[ssh-agent]         ... 10 more
[ssh-agent]     Caused by: java.lang.ExceptionInInitializerError
[ssh-agent]         at jnr.ffi.provider.jffi.NativeRuntime.getInstance(NativeRuntime.java:49)
[ssh-agent]         at jnr.ffi.provider.jffi.Provider.<init>(Provider.java:29)
[ssh-agent]         at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[ssh-agent]         at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[ssh-agent]         at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[ssh-agent]         at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[ssh-agent]         at java.lang.Class.newInstance(Class.java:442)
[ssh-agent]         at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.getInstance(FFIProvider.java:60)
[ssh-agent]         at jnr.ffi.provider.FFIProvider$SystemProviderSingletonHolder.<clinit>(FFIProvider.java:49)
[ssh-agent]         at jnr.ffi.provider.FFIProvider.getSystemProvider(FFIProvider.java:35)
[ssh-agent]         at jnr.ffi.Runtime$SingletonHolder.<clinit>(Runtime.java:85)
[ssh-agent]         at jnr.ffi.Runtime.getSystemRuntime(Runtime.java:70)
[ssh-agent]         at jnr.unixsocket.SockAddrUnix.<init>(SockAddrUnix.java:34)
[ssh-agent]         at jnr.unixsocket.SockAddrUnix$DefaultSockAddrUnix.<init>(SockAddrUnix.java:128)
[ssh-agent]         at jnr.unixsocket.SockAddrUnix.create(SockAddrUnix.java:99)
[ssh-agent]         at jnr.unixsocket.UnixSocketAddress.<init>(UnixSocketAddress.java:32)
[ssh-agent]         at com.cloudbees.jenkins.plugins.sshagent.jna.AgentServer.start(AgentServer.java:80)
[ssh-agent]         at com.cloudbees.jenkins.plugins.sshagent.jna.JNRRemoteAgent.<init>(JNRRemoteAgent.java:68)
[ssh-agent]         at com.cloudbees.jenkins.plugins.sshagent.jna.JNRRemoteAgentStarter.call(JNRRemoteAgentStarter.java:63)
[ssh-agent]         at com.cloudbees.jenkins.plugins.sshagent.jna.JNRRemoteAgentStarter.call(JNRRemoteAgentStarter.java:37)
[ssh-agent]         at hudson.remoting.UserRequest.perform(UserRequest.java:121)
[ssh-agent]         at hudson.remoting.UserRequest.perform(UserRequest.java:49)
[ssh-agent]         at hudson.remoting.Request$2.run(Request.java:324)
[ssh-agent]         at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:68)
[ssh-agent]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[ssh-agent]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[ssh-agent]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[ssh-agent]         at hudson.remoting.Engine$1$1.run(Engine.java:63)
[ssh-agent]         at java.lang.Thread.run(Thread.java:745)
[ssh-agent]     Caused by: java.lang.IllegalStateException: Can't overwrite cause with java.lang.UnsatisfiedLinkError
[ssh-agent]         at java.lang.Throwable.initCause(Throwable.java:457)
[ssh-agent]         at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:252)
[ssh-agent]         at com.kenai.jffi.Type$Builtin.getTypeInfo(Type.java:237)
[ssh-agent]         at com.kenai.jffi.Type.resolveSize(Type.java:155)
[ssh-agent]         at com.kenai.jffi.Type.size(Type.java:138)
[ssh-agent]         at jnr.ffi.provider.jffi.NativeRuntime$TypeDelegate.size(NativeRuntime.java:178)
[ssh-agent]         at jnr.ffi.provider.AbstractRuntime.<init>(AbstractRuntime.java:48)
[ssh-agent]         at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:57)
[ssh-agent]         at jnr.ffi.provider.jffi.NativeRuntime.<init>(NativeRuntime.java:41)
[ssh-agent]         at jnr.ffi.provider.jffi.NativeRuntime$SingletonHolder.<clinit>(NativeRuntime.java:53)
[ssh-agent]         ... 29 more
[ssh-agent]     Caused by: java.lang.UnsatisfiedLinkError
[ssh-agent]         at com.kenai.jffi.Foreign.newLoadError(Foreign.java:72)
[ssh-agent]         at com.kenai.jffi.Foreign.access$300(Foreign.java:42)
[ssh-agent]         at com.kenai.jffi.Foreign$InValidInstanceHolder.getForeign(Foreign.java:98)
[ssh-agent]         at com.kenai.jffi.Foreign.getInstance(Foreign.java:103)
[ssh-agent]         at com.kenai.jffi.Type$Builtin.lookupTypeInfo(Type.java:242)
[ssh-agent]         ... 37 more
[ssh-agent]     Caused by: java.lang.UnsatisfiedLinkError: could not locate stub library in jar file.  Tried [jni/unknown-Linux/libjffi-1.2.so, /jni/unknown-Linux/libjffi-1.2.so]
[ssh-agent]         at com.kenai.jffi.internal.StubLoader.getStubLibraryStream(StubLoader.java:353)
[ssh-agent]         at com.kenai.jffi.internal.StubLoader.loadFromJar(StubLoader.java:300)
[ssh-agent]         at com.kenai.jffi.internal.StubLoader.load(StubLoader.java:235)
[ssh-agent]         at com.kenai.jffi.internal.StubLoader.<clinit>(StubLoader.java:403)
[ssh-agent]         at java.lang.Class.forName0(Native Method)
[ssh-agent]         at java.lang.Class.forName(Class.java:348)
[ssh-agent]         at com.kenai.jffi.Init.load(Init.java:68)
[ssh-agent]         at com.kenai.jffi.Foreign$InstanceHolder.getInstanceHolder(Foreign.java:49)
[ssh-agent]         at com.kenai.jffi.Foreign$InstanceHolder.<clinit>(Foreign.java:45)
[ssh-agent]         ... 39 more
FATAL: [ssh-agent] Unable to start agent
hudson.util.IOException2: [ssh-agent] Unable to start agent
    at com.cloudbees.jenkins.plugins.sshagent.SSHAgentBuildWrapper.createSSHAgentEnvironment(SSHAgentBuildWrapper.java:253)
    at com.cloudbees.jenkins.plugins.sshagent.SSHAgentBuildWrapper.preCheckout(SSHAgentBuildWrapper.java:223)
    at jenkins.scm.SCMCheckoutStrategy.preCheckout(SCMCheckoutStrategy.java:76)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:528)
    at hudson.model.Run.execute(Run.java:1738)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Caused by: java.lang.RuntimeException: [ssh-agent] Could not find a suitable ssh-agent provider.
    at com.cloudbees.jenkins.plugins.sshagent.SSHAgentBuildWrapper$SSHAgentEnvironment.<init>(SSHAgentBuildWrapper.java:371)
    at com.cloudbees.jenkins.plugins.sshagent.SSHAgentBuildWrapper.createSSHAgentEnvironment(SSHAgentBuildWrapper.java:246)
    ... 7 more
```

**Comment by tfoote** [comment]
There's a new approach for the ssh-agent: https://issues.jenkins-ci.org/browse/JENKINS-36997
