### ISSUE TITLE
jenkins remoting issue on sourcdeb jobs

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/buildfarm_deployment#87]
The connection was dropped at the very end and caused a failure?

http://build.ros.org:8080/job/Isrc_uS__libntcan__ubuntu_saucy__source/4/console

```
# BEGIN SECTION: Clean up to save disk space on slaves
06:36:46 + rm -fr sourcedeb/source
06:36:46 + echo # END SECTION
06:36:46 # END SECTION
06:36:46 SSH: Connecting from host [ip-172-31-6-103]
06:36:46 SSH: Connecting with configuration [repo] ...
06:36:46 SSH: Disconnecting configuration [repo] ...
06:36:46 SSH: Transferred 4 file(s)
06:36:46 Build step 'Send files or execute commands over SSH' changed build result to SUCCESS
06:36:51 Waiting for the completion of Irel_import-package
06:44:24 Irel_import-package #2844 completed. Result was SUCCESS
06:44:24 FATAL: java.io.IOException: Backing channel is disconnected.
06:44:24 hudson.remoting.RemotingSystemException: java.io.IOException: Backing channel is disconnected.
06:44:24 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:266)
06:44:24 	at com.sun.proxy.$Proxy51.stop(Unknown Source)
06:44:24 	at com.cloudbees.jenkins.plugins.sshagent.SSHAgentBuildWrapper$SSHAgentEnvironment.tearDown(SSHAgentBuildWrapper.java:407)
06:44:24 	at hudson.model.Build$BuildExecution.doRun(Build.java:173)
06:44:24 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
06:44:24 	at hudson.model.Run.execute(Run.java:1741)
06:44:24 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
06:44:24 	at hudson.model.ResourceController.execute(ResourceController.java:98)
06:44:24 	at hudson.model.Executor.run(Executor.java:408)
06:44:24 Caused by: java.io.IOException: Backing channel is disconnected.
06:44:24 	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:185)
06:44:24 	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:250)
06:44:24 	... 8 more
06:44:24 [description-setter] Could not determine description.
06:44:24 ERROR: Step ‘E-mail Notification’ failed: no workspace for Isrc_uS__libntcan__ubuntu_saucy__source #4
06:44:24 Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
06:44:27 Finished: FAILURE
```

Watching the web UI, I've also seen executors briefly reporting "Dead" in red which might be releated.

**Comment by tfoote** [comment]
This is minor and recoverable but increases the failure rate. There are some documentation on debugging this here: https://wiki.jenkins-ci.org/display/JENKINS/Remoting+issue

**Comment by tfoote** [comment]
I have not seen this continue to repeat. It might have been a temporary connectivity issue. Or been related to the high load of repeated connections to the same job during the bootstrap phase. I'm going to close for now since it's not recurring and there's no way to debug it without that.
